version: 2.1

jobs:
  build:
    machine:
      # docker composeが使えるイメージを選択
      image: circleci/classic:edge
    working_directory: ~/111111
    steps:
      - checkout
      - run:
          name: "環境構築"
          working_directory: ~/
          command: |
            sudo tee -a /etc/hosts \<<<'127.0.0.1 local.shareg.com'
            git clone git@github.com:FIELDASIA/SHAREG_docker.git
            mkdir ~/PMS_docker/apps
            mv ~/seven-garden/.env4circleci ~/seven-garden/.env
            mv ~/seven-garden ~/PMS_docker/apps
      - run:
          name: "コンテナのビルド"
          working_directory: ~/PMS_docker
          command: |
            docker-compose build
      - run:
          name: "コンテナの立ち上げ"
          working_directory: ~/PMS_docker
          command: |
            docker-compose up -d
      - run:
          name: "DB初期化"
          working_directory: ~/PMS_docker
          command: |
            sleep 60 && docker-compose exec mysql sh -c "/bin/echo 'create database pms_local' | /usr/bin/mysql -uroot -proot"
      - run:
          name: "初期設定"
          working_directory: ~/PMS_docker
          command: |
            docker-compose exec php sh -c "cd seven-garden && /usr/local/bin/composer install"
            docker-compose exec php sh -c "cd seven-garden && /usr/local/bin/php artisan key:generate"
            docker-compose exec php sh -c "cd seven-garden && /usr/local/bin/php artisan storage:link"
            docker-compose exec php sh -c "cd seven-garden && /bin/chmod -R 777 storage/"
            docker-compose exec php sh -c "cd seven-garden && /usr/local/bin/php artisan migrate"
            docker-compose exec php sh -c "cd seven-garden && /usr/local/bin/php artisan db:seed"
      - run:
          name: "テスト"
          working_directory: ~/PMS_docker/apps/seven-garden
          command: |
            docker-compose exec php sh -c "cd seven-garden && vendor/bin/phpunit tests/Unit/ExampleTest.php"
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
          # circle ciで登録した秘密鍵のfingerprint
          fingerprints:
            - "62:bd:fb:ce:92:f8:f4:e8:ad:5e:96:44:e2:ac:f1:67"
      # ステージング環境で実行したいコマンド
      - run: ssh ${STG_USER}@${STG_HOST} 'cd ~ && pwd'

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          # 先にbuildを実行させるためbuildのジョブに依存させる
          requires:
            - build
          filters:
            branches:
              # pull requestのマージでdeployジョブを実行させるブランチ
              only: circleci-deploy-test