<?php

return [
    'migrations' => [
        'skip_admins' => env('MIGRATIONS_SKIP_ADMINS', false),
        'skip_clients' => env('MIGRATIONS_SKIP_CLIENTS', false),
        'skip_hotels' => env('MIGRATIONS_SKIP_HOTELS', false),
        'skip_hotel_kids_policies' => env('MIGRATIONS_SKIP_HOTEL_KIDS_POLICIES', false),
        'skip_hotel_notes' => env('MIGRATIONS_SKIP_HOTEL_NOTES', false),
        'skip_hotel_room_types' => env('MIGRATIONS_SKIP_HOTEL_ROOM_TYPES', false),
        'skip_hotel_room_type_beds' => env('MIGRATIONS_SKIP_HOTEL_ROOM_TYPE_BEDS', false),
        'skip_hotel_room_type_images' => env('MIGRATIONS_SKIP_HOTEL_ROOM_TYPE_IMAGES', false),
        'skip_hotel_hard_categories' => env('MIGRATIONS_SKIP_HOTEL_CATEGORIES', false),
        'skip_hotel_hard_items' => env('MIGRATIONS_SKIP_HOTEL_ITEMS', false),
        'skip_cancel_policies' => env('MIGRATIONS_SKIP_CANCEL_POLICIES', false),
        'skip_plans' => env('MIGRATIONS_SKIP_PLANS', false),
        'skip_components' => env('MIGRATIONS_SKIP_COMPONENTS', false),
        'skip_original_lps' => env('MIGRATIONS_SKIP_ORIGINAL_LPS', false),
        'skip_original_lp_layouts' => env('MIGRATIONS_SKIP_ORIGINAL_LP_LAYOUTS', false),
        'skip_original_lp_layout_conditions' => env('MIGRATIONS_SKIP_ORIGINAL_LP_LAYOUT_CONDITIONS', false),
        'skip_rate_plans' => env('MIGRATIONS_SKIP_RATE_PLANS', false),
        'skip_images' => env('MIGRATIONS_SKIP_IMAGES', false),
        'skip_layouts' => env('MIGRATIONS_SKIP_LAYOUTS', false),
        'skip_lps' => env('MIGRATIONS_SKIP_LPS', false),
        'skip_lp_layouts' => env('MIGRATIONS_SKIP_LP_LAYOUTS', false),
        'skip_lp_layout_conditions' => env('MIGRATIONS_SKIP_LP_LAYOUT_CONDITIONS', false),
        'skip_forms' => env('MIGRATIONS_SKIP_FORMS', false),
        'skip_form_items' => env('MIGRATIONS_SKIP_FORM_ITEMS', false),
        'skip_reservations' => env('MIGRATIONS_SKIP_RESERVATIONS', false),
        'skip_reservation_plans' => env('MIGRATIONS_SKIP_RESERVATION_PLANS', false),
        'skip_reservation_plan_form_items' => env('MIGRATIONS_SKIP_RESERVATION_PLAN_FORM_ITEMS', false),
        'skip_reservation_refund' => env('MIGRATIONS_SKIP_RESERVATION_REFUND', false),
        'skip_hotel_month_fee_summary' => env('MIGRATIONS_SKIP_HOTEL_MONTH_FEE_SUMMARY', false),
        'skip_original_hotel_hard_categories' => env('MIGRATIONS_SKIP_ORIGINAL_HOTEL_CATEGORIES', false),
        'skip_original_hotel_hard_items' => env('MIGRATIONS_SKIP_ORIGINAL_HOTEL_ITEMS', false),
        'skip_reservation_captured' => env('MIGRATIONS_SKIP_RESERVATION_CAPTURED', false),
        'skip_reservation_authory' => env('MIGRATIONS_SKIP_RESERVATION_AUTHORY', false),
        'skip_reservation_payment' => env('MIGRATIONS_SKIP_RESERVATION_PAYMENT', false),
        'skip_reservation_blocks' => env('MIGRATIONS_SKIP_RESERVATION_BLOCKS', false),
        'skip_reservation_repeat_groups' => env('MIGRATIONS_SKIP_RESERVATION_REPEAT_GROUPS', false),
        'skip_reserved_reservation_blocks' => env('MIGRATIONS_SKIP_RESERVED_RESERVATION_BLOCKS', false),
        'skip_base_customer_item_values' => env('MIGRATIONS_SKIP_BASE_CUSTOMER_ITEM_VALUES', false),
    ],

    'seeds' => [
        'skip_admin' => env('SEEDS_SKIP_ADMIN', false),
        'skip_client' => env('SEEDS_SKIP_CLIENT', false),
        'skip_component' => env('SEEDS_SKIP_COMPONENT', false),
        'skip_image' => env('SEEDS_SKIP_IMAGE', false),
        'skip_rateplan' => env('SEEDS_SKIP_RATEPLAN', false),
        'skip_lp_category' => env('SEEDS_SKIP_LP_CATEGORY', false),
        'skip_form' => env('SEEDS_SKIP_FORM', false),
        'skip_hotel_kids_policy' => env('SEEDS_SKIP_HOTEL_KIDS_POLICY', false),
        'skip_hotel_room_type' => env('SEEDS_SKIP_HOTEL_ROOM_TYPE', false),
        'skip_lp' => env('SEEDS_SKIP_LP', false),
        'skip_form' => env('SEEDS_SKIP_FORM', false),
        'skip_plan' => env('SEEDS_SKIP_PLAN', false),
        'skip_cancel_policy' => env('SEEDS_SKIP_CANCEL_POLICY', false),
        'skip_room_stock'=> env('SEEDS_SKIP_ROOM_STOCK', false),
        'skip_room_type_bed'=> env('SEEDS_SKIP_ROOM_TYPE_BED', false),
        'skip_room_type_image'=> env('SEEDS_SKIP_ROOM_TYPE_IMAGE', false),
        'skip_plan_room_type_rates'=> env('SEEDS_SKIP_PLAN_ROOM_TYPE_RATE', false),
        'skip_plan_room_type_rates_per_class'=> env('SEEDS_SKIP_PLAN_ROOM_TYPE_RATE_PER_CLASS', false),
        'skip_original_layout' => env('SEEDS_SKIP_ORIGINAL_LAYOUT', false),
        'skip_layout' => env('SEEDS_SKIP_LAYOUT', false),
        'skip_original_lp' => env('SEEDS_SKIP_ORIGINAL_LP', false),
        'skip_hotel_note' => env('SEEDS_SKIP_HOTEL_NOTE', false),
    ],

];
